name: Lint
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install black isort
      - name: Run black
        run: black . --target-version py39 --diff --check
      - name: Run isort
        run: isort . --check --diff --profile black
